TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.05
  max_rotational_vel: 1.5
  min_in_place_rotational_vel: 0.1

  acc_lim_th: 2.5
  acc_lim_x: 1.0
  acc_lim_y: 1.0

  holonomic_robot: false

  xy_goal_tolerance: 0.2
  yaw_goal_tolerance: 3.15
