global_costmap:
   global_frame: /map
   robot_base_frame: /base_link
   map_type: costmap
   update_frequency: 2.0
   publish_frequency: 0.0
   static_map: false
   rolling_window: true
   transform_tolerance: 0.5
   width: 50
   height: 50
   resolution: 0.05
