footprint: [[-0.3,-0.35], [-0.3,0.35], [1.0,0.35], [1.0,-0.35] ]
footprint_padding: 0.2

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 10.0

resolution: 0.05

obstacle_range: 4.5
raytrace_range: 4.5
cost_scaling_factor: 30
inflation_radius: 15

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, clearing: true, marking: true, topic: /base_scan, sensor_frame: /laser, inf_is_valid: true}

inflation:
    inflation_radius: 0.8

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
