obstacle_range: 2.5
raytrace_range: 3.0
footprint: [ [-0.2,-0.35], [-0.2,0.35], [0.6,0.35], [0.6,-0.35] ]
inflation_radius: 0.8

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /base_laser_link, data_type: LaserScan, topic: /base_scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
