image: /home/bas/catkin_ws/src/ROS_uts_cas_wheelchair/goto_box_project/goto_box/config/map/UTS_map4.pgm
resolution: 0.010000
origin: [-20.004999, -20.004999, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

